### ISSUE TITLE
checkpoint

### ISSUE THREAD

**Issue by 649459021** [shercoo/RGDiffSR#1]
Hi，
Thanks for releasing this nice work!

I notice there is just an empty folder in [Baidu Netdisk](https://pan.baidu.com/s/1SV7GHY0kfHB6s7eC3tUFqA?pwd=yws3).
Will you release the pretrained checkpoint?

Looking forward to your reply~

**Comment by shercoo** [comment]
The .ckpt file is now uploaded .

**Comment by 649459021** [comment]
Thanks :)
